# Check https://circleci.com/docs/2.0/language-java/ for more details
version: 2.1
jobs:
   build:
      machine:
         image: ubuntu-1604:201903-01
      working_directory: ~/repo
      environment:
         MAVEN_OPTS: -Xmx3200m
      steps:
      - checkout
      -  restore_cache:
            keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      -  run: mvn dependency:go-offline
      -  save_cache:
            paths:
            - ~/.m2
            key: v1-dependencies-{{ checksum "pom.xml" }}
      -  run: mvn verify
      -  run: bash <(curl -s https://codecov.io/bash)
   sonar:
      docker:
      -  image: circleci/openjdk:11-jdk
      steps:
      - checkout
      -  run: mvn verify sonar:sonar -DskipTests -Dsonar.branch.name=${CIRCLE_BRANCH}
      -  run: ./.circleci/sonar_build_breaker.sh
   vulnerability:
      docker:
      -  image: circleci/openjdk:11-jdk
      steps:
      - checkout
      -  run: mvn org.owasp:dependency-check-maven:5.2.4:check -DfailBuildOnAnyVulnerability=true
workflows:
   main:
      jobs:
      - build
      -  sonar:
            context: SonarCloud
            requires:
            - build
   nightly:
      triggers:
      -  schedule:
            cron: 0 0 * * *
            filters:
               branches:
                  only:
                  - master
      jobs:
      - vulnerability