# Check https://circleci.com/docs/2.0/language-java/ for more details
version: 2.1
jobs:
   build:
      machine:
         image: ubuntu-1604:201903-01
      working_directory: ~/repo
      environment:
         MAVEN_OPTS: -Xmx3200m
      steps:
      - checkout
      -  restore_cache:
            keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      -  run: mvn dependency:go-offline
      -  save_cache:
            paths:
            - ~/.m2
            key: v1-dependencies-{{ checksum "pom.xml" }}
      -  run: mvn verify
      -  run: bash <(curl -s https://codecov.io/bash)